config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  resources :categories
  resources :articles
  get 'welcome/about'

  namespace :admin do
    get '' => 'articles#index'
    resources :articles
    resources :categories
    resources :images
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  
  validates :title, presence: true
  validates :category_id, presence: true

  mount_uploader :logo, LogoUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  mount_uploader :image, LogoUploader
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseAdminController
  def index
    @articles = Article.all.order('id desc')
  end

  def create
    @article = Article.new article_params
    if @article.save
      flash[:notice] = 'Makale başarı ile eklendi'
      redirect_to admin_path
    else
      render :new
    end
  end

  def edit
    @articles = Article.find(params[:id])
    @category = Category.all
  end

  def new
    @articles = Article.new
    @category = Category.all
  end

  def update
    @article = Article.find params[:id]
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_path, notice: 'Makale Güncellendi' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def article_params
    params.require(:article).permit!
  end
end

app/controllers/admin/base_admin_controller.rb
class Admin::BaseAdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseAdminController
  def show
    @category = Category.find params[:id]
  end
end

app/controllers/admin/image_controller.rb
class Admin::ImageController < ApplicationController
  def new
    @image=Image.new
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseAdminController
  def new
    @images = Image.new
  end

  def create
  	@images = Image.new image_params
  	if @images.save
      flash[:notice] = 'Makale başarı ile eklendi'
      redirect_to admin_image_path(@images.id)
    else
      render :new
    end
  end

  def show
  	@images = Image.find params[:id]
  end

  private
  def image_params
    params.require(:image).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def change_image

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order('id desc')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
      @category = Category.find params[:id]
      @images = Image.where.not("id = 24 OR id = 27 OR id = 28")
  end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.order('id desc')
  end
  def about
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_admin_helper.rb
module Admin::BaseAdminHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/image_helper.rb
module Admin::ImageHelper
end

app/helpers/admin/yonet_helper.rb
module Admin::YonetHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/_article.html.erb
<dt><%= article.title %></dt><blockquote><%= article.description%></blockquote><dd class="th"><%= image_tag article.logo.thumb.url if article.logo.present?%></dd><p><%= article.text%></p>

app/views/admin/articles/edit.html.erb
<%= form_for [:admin, @articles], data: {abide: ''} do |form| %>    <% if @articles.errors.any? %>        <div class="row">          <p>Aşagidaki hatalari düzeltip tekrar deneyiniz</p>          <ul class="square">            <% @articles.errors.full_messages.each do |message| %>                <li><%= message %></li>            <% end %>          </ul>        </div>    <% end %>    <br><br>    <div>      <div>        <%= form.label "Kategori Seç:"%>        <%= form.collection_select :category_id, @category, :id, :name, {}, {:class=>'small'} %>      </div>      <br>      <div>        <%= form.label "Makale Başlığı:" %>        <%= form.text_field :title, required: true %>      </div>      <div>        <%= form.label "Açıklama Gir:" %>        <%= form.text_field :description, required: true %>      </div>      <br>      <div>        <%= form.label "Makale metini:" %>        <%= form.text_area :text, required: true %>      </div>      <br>      <div>        <%= form.label "Makale Resmi:" %>        <%= form.file_field :logo %>      </div>      <br>      <div>        <%= form.submit %>      </div>    </div><% end %><br>

app/views/admin/articles/index.html.erb
<div align="left">  <table>    <% @articles.each do |article| %>        <dt><%= article.title %></dt>        <blockquote><%= article.description%></blockquote>        <%= image_tag article.logo.thumb.url if article.logo.present? %>        <hr>    <% end %>  </table></div>

app/views/admin/articles/new.html.erb
<%= form_for [:admin, @articles], data: {abide: ''} do |form| %>    <% if @articles.errors.any? %>        <div class="row">          <p>Aşagidaki hatalari düzeltip tekrar deneyiniz</p>          <ul class="square">            <% @articles.errors.full_messages.each do |message| %>                <li><%= message %></li>            <% end %>          </ul>        </div>    <% end %>    <br><br>    <div>      <div>        <%= form.label "Kategori Seç:"%>        <%= form.collection_select :category_id, @category, :id, :name, {}, {:class=>'small'} %>      </div>      <br>      <div>        <%= form.label "Makale Başlığı:" %>        <%= form.text_field :title, required: true %>      </div>      <div>        <%= form.label "Açıklama Gir:" %>        <%= form.text_field :description, required: true %>      </div>      <br>      <div>        <%= form.label "Makale metni:" %>        <%= form.text_area :text, required: true %>      </div>      <br>      <div>        <%= form.label "Makale Resmi:" %>        <%= form.file_field :logo %>      </div>      <br>      <div>        <%= form.submit %>      </div>    </div><% end %>

app/views/admin/categories/show.html.erb
<h3><%=@category.name %> makaleleri</h3><table border="1"><% @category.articles.each do |article|%>    <tr>      <td><%= render article %> <%= link_to "Edit", edit_admin_article_path(article) %></td>    </tr><%end%></table>

app/views/admin/image/new.html.erb
<%= form_for [:admin, @images], data: {abide: ''} do |form| %>    <% if @images.errors.any? %>        <div class="row">          <p>Incorrect values</p>          <ul class="square">            <% @images.errors.full_messages.each do |message| %>                <li><%= message %></li>            <% end %>          </ul>        </div>    <% end %>    <br><br>    <div>      <br>      <div>        <%= form.label "Image Title:" %>        <%= form.text_area :title, required: true %>      </div>      <br>      <div>        <%= form.label "Image:" %>        <%= form.file_field :image %>      </div>      <br>      <div>        <%= form.submit %>      </div>    </div><% end %>

app/views/admin/images/new.html.erb
<%= form_for [:admin, @images], data: {abide: ''} do |form| %>    <div>      <br>      <div>        <%= form.label "Image Title:" %>        <%= form.text_area :title, required: true %>      </div>      <br>      <div>        <%= form.label "Image:" %>        <%= form.file_field :image %>      </div>      <br>      <div>        <%= form.submit %>      </div>    </div><% end %>

app/views/admin/images/show.html.erb
<table>
  <tr>
	<td><%= image_tag @images.image.url(:thumb) %></td>
  </tr>
</table>

app/views/articles/_article.html.erb
<dt><%= article.title %></dt>
<blockquote><%= article.description%></blockquote>
<% if article.logo.present? %>
    <div>
      <ul class="clearing-thumbs small-block-grid-4" data-clearing>
    <li><a href="<%= article.logo.thumb.url %>">
      <img src="<%= article.logo.thumb.url %>"></a></li>
          </ul>
        </div>
<% end %>
<p><%= article.text%></p>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
    <dl>
      <%= render article %>
    </dl>
    <hr>
<%end%>

app/views/categories/show.html.erb
<% if @category.name == 'Galeri' %>
    <br>
    <div>
      <ul class="clearing-thumbs small-block-grid-4" data-clearing>
        <% @images.each do |image| %>
            <% if image.image.present? %>
                <li><a href="<%= image.image.thumb.url %>">
                  <img data-caption="<%= image.title %>" src="<%= image.image.thumb.url %>"></a></li>
            <% end %>
        <% end %>
      </ul>
      <div>
<% else %>
    <h3><%= @category.name %> articles</h3>
    <% @category.articles.each do |article| %>
        <dl>
          <%= render article %>
        </dl>
        <hr>
    <% end %>
<% end %>