config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  resources :categories
  resources :articles
  get 'welcome/about'

  namespace :admin do
    get '' => 'articles#index'
    resources :articles
    resources :categories
    resources :images
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  
  validates :title, presence: true
  validates :category_id, presence: true

  mount_uploader :logo, LogoUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  mount_uploader :image, LogoUploader
end

app/controllers/admin/image_controller.rb
class Admin::ImageController < ApplicationController
  def new
    @image=Image.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def change_image

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order('id desc')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
      @category = Category.find params[:id]
      @images = Image.where.not("id = 24 OR id = 27 OR id = 28")
  end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.order('id desc')
  end
  def about
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_admin_helper.rb
module Admin::BaseAdminHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/image_helper.rb
module Admin::ImageHelper
end

app/helpers/admin/yonet_helper.rb
module Admin::YonetHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html><html lang="en"><head>  <meta charset="utf-8" />  <meta name="viewport" content="width=device-width, initial-scale=1.0" />  <title><%= content_for?(:title) ? yield(:title) : "" %></title>  <%= stylesheet_link_tag    'application' %>  <%= javascript_include_tag 'vendor/modernizr' %>  <%= csrf_meta_tags %></head><body><ul class="title-area">  <h5><a href="/admin">Admin Paneli</a></h5></ul><section class="top-bar-section">  <table>    <tr>      <td><%=link_to "Bilg. Blm. Yönet", admin_category_path(1) %></td>      <td><%=link_to "Seyahatleri Yönet" , admin_category_path(2)%></td>      <td><%=link_to "Edebiyatları Yönet", admin_category_path(3)%></td>      <td><%=link_to "Galerileri Yönet", admin_category_path(4)%></td>      <td><a href="<%=admin_articles_path%>">Arşivi Yönet</a></td>      <td><a href="<%=admin_articles_path%>">Hakkımdayı Yönet</a>      <td><%=link_to "++Yeni Makale", new_admin_article_path%><br>          <%=link_to "++Yeni Resim", new_admin_image_path %></td>    </tr>  </table></section><div class="row">  <%= yield %>  <%= javascript_include_tag "application" %></div></body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<center>
  <div class="orbit-container">
    <ul class="example-orbit" data-orbit>
      <li>
        <img src="/uploads/image/image/24/thumb_budapeste1.jpg" alt="slide 1"/>
        <div class="orbit-caption">
          Budapest
        </div>
      </li>
      <li class="active">
        <img src="/uploads/image/image/27/thumb_istanbul.jpg" alt="slide 2"/>
        <div class="orbit-caption">
          Istanbul
        </div>
      </li>
      <li>
        <img src="/uploads/image/image/28/thumb_antakya_site_2.jpg" alt="slide 3"/>
        <div class="orbit-caption">
          Antakya
        </div>
      </li>
    </ul>
  </div>
</center>

<body>
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Home</a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul>
        <li class="divider"></li>
        <li><%= link_to "Computer Science", category_path(1) %></li>
        <li class="divider"></li>
        <li><%= link_to "Travels", category_path(2) %></li>
        <li class="divider"></li>
        <li><%= link_to "Art", category_path(3) %></li>
        <li class="divider"></li>
        <li><%= link_to "Gallery", category_path(4) %></li>
        <li class="divider"></li>
      </ul>
      <ul class="right">
        <li><a href="<%= articles_path %>">Archive</a></li>
        <li class="divider"></li>
        <li><a href="<%= welcome_about_path %>">About Me</a></li>
      </ul>
    </section>
  </nav>
</div>

<div class="row">
  <%= yield %>
</div>
<%= javascript_include_tag "application" %>
<footer>
  Copyright &copy; 2014 sadikay.com
</footer>
</body>
</html>